### PR TITLE
Allow adding labels.

### PR DESCRIPTION
**Pull request by jgoclawski**
Example usage: `kubepy-apply-one --label build_number=123 deployment`

---
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/kubepy/22)

### CODE REVIEW

**Comment by jgoclawski** [comment]
@maruqu Please take a look.

After #21 is merged I will rebase this PR on master, because only the latest commit is relevant.

**Comment by maruqu** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/22#-:-L3mrjkEca0myG6oofcC:bnfp4nl)*

**Comment by maruqu** [comment]
Reviewed 6 of 6 files at r1.
Review status: 5 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/22)*

**Comment by maruqu** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/22#-:-L3ms5uHN2DQRO1rnluA:bnfp4nl)*

**Pull request merged**
