### PR TITLE
Allow to mount development volume.

### PR DESCRIPTION
**Pull request by kramarz**
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/kubepy/13)

### CODE REVIEW

**Comment by jgoclawski** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kubepy/appliers.py, line 39 at r3](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-KaDFTx8Q680Yi9SEwXO:-KaDFTx8Q680Yi9SEwXP:b-s3z3h0) ([raw file](https://github.com/socialwifi/kubepy/blob/780ddb4ea400fcd8e1eb3b2465e09391e4375af8/kubepy/appliers.py#L39)):*
> ```Python
> 
> def directories_applier(paths, options):
>     manager = definition_manager.OverridedDefinitionManager(
> ```

"Overrided" -> "Overriden"

---

*[kubepy/definition_manager.py, line 20 at r2](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-KaDEbmt77sMJA1Cm7EQ:-KaDEbmukHZ1M5B7xsZs:bjpofaq) ([raw file](https://github.com/socialwifi/kubepy/blob/90efa1b8ef0348b60aaf5d3c6e96cc6404e4b7fb/kubepy/definition_manager.py#L20)):*
> ```Python
> 
>     def __len__(self):
>         return len(list(self.directory.glob('*.yml')))
> ```

would something like `return len(list(self))` work as well? It would be great to keep `__len__` and `__iter__` DRY and consistent.

---

*[kubepy/definition_manager.py, line 26 at r2](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-KaDE8CU-Nmxfco3x_90:-KaDE8CU-Nmxfco3x_91:b-zqyqt) ([raw file](https://github.com/socialwifi/kubepy/blob/90efa1b8ef0348b60aaf5d3c6e96cc6404e4b7fb/kubepy/definition_manager.py#L26)):*
> ```Python
>             return yaml.load(yaml_file)
> 
>     def get_path_from_name(self, name):
> ```

this function should be above `get_yaml_from_file` (order of usage in `__getitem__`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/13)*

**Comment by kramarz** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[kubepy/appliers.py, line 39 at r3](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-KaDFTx8Q680Yi9SEwXO:-KaGuLXY6EWjZC-2fWe8:b-896fix) ([raw file](https://github.com/socialwifi/kubepy/blob/780ddb4ea400fcd8e1eb3b2465e09391e4375af8/kubepy/appliers.py#L39)):*
<details><summary><i>Previously, jgoclawski (Jakub Gocławski) wrote…</i></summary><blockquote>

"Overrided" -> "Overriden"
</blockquote></details>

Done.

---

*[kubepy/definition_manager.py, line 20 at r2](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-KaDEbmt77sMJA1Cm7EQ:-KaGrwuCe_qT-XD1ULP1:b-896fix) ([raw file](https://github.com/socialwifi/kubepy/blob/90efa1b8ef0348b60aaf5d3c6e96cc6404e4b7fb/kubepy/definition_manager.py#L20)):*
<details><summary><i>Previously, jgoclawski (Jakub Gocławski) wrote…</i></summary><blockquote>

would something like `return len(list(self))` work as well? It would be great to keep `__len__` and `__iter__` DRY and consistent.
</blockquote></details>

Done.

---

*[kubepy/definition_manager.py, line 26 at r2](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-KaDE8CU-Nmxfco3x_90:-KaGsRbCsIIf3LWGzpph:b-896fix) ([raw file](https://github.com/socialwifi/kubepy/blob/90efa1b8ef0348b60aaf5d3c6e96cc6404e4b7fb/kubepy/definition_manager.py#L26)):*
<details><summary><i>Previously, jgoclawski (Jakub Gocławski) wrote…</i></summary><blockquote>

this function should be above `get_yaml_from_file` (order of usage in `__getitem__`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/13)*

**Comment by jgoclawski** [comment]
Reviewed 9 of 9 files at r7, 5 of 5 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/13)*

**Comment by jgoclawski** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/kubepy/13#-:-KaId7eshHxJ3GEvlbWZ:bnfp4nl)*

**Pull request merged**
